# generated by datamodel-codegen:
#   filename:  occurrence.json
#   timestamp: 2026-02-25T08:45:29+00:00

from __future__ import annotations

from pydantic import BaseModel


class Survey(BaseModel):
    """Contents of 'values' in a list of surveys"""

    id: str
    title: str
    description: str
    website_id: str
    created_on: str
    created_by_id: str
    updated_on: str
    updated_by_id: str
    parent_id: None


class Values(BaseModel):
    survey_id: int
    entered_sref: str
    entered_sref_system: str
    date: str


class Occurrence(BaseModel):
    taxa_taxon_list_id: int
    # TBC


class MediaItem(BaseModel):
    queued: str
    caption: str


class OccurrencePost(BaseModel):
    values: Occurrence
    media: list[MediaItem]
