# generated by datamodel-codegen:
#   filename:  occurrence.json
#   timestamp: 2026-02-25T08:45:29+00:00

from __future__ import annotations

from typing import List, Optional
from pydantic import BaseModel


class Survey(BaseModel):
    """Contents of 'values' in a list of surveys"""

    id: str
    title: str
    description: str
    website_id: str
    created_on: str
    created_by_id: str
    updated_on: str
    updated_by_id: str
    parent_id: None


class Sample(BaseModel):
    survey_id: int
    entered_sref: str
    entered_sref_system: str
    date: str


class Occurrence(BaseModel):
    taxa_taxon_list_id: int
    # Occurrence Attributes which have the key occAttr:N where N is an integer ID
    # Their use is restricted to specific surveys; we can't enumerate them here.


class MediaPost(BaseModel):
    values: MediaItem


class MediaItem(BaseModel):
    queued: str
    caption: str


class OccurrencePost(BaseModel):
    values: Occurrence
    media: Optional[list[MediaPost]]


class SamplePost(BaseModel):
    values: Sample
    occurrences: List[OccurrencePost]
